version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: ecommerce-postgres

    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:7
    container_name: ecommerce-redis

    ports:
      - "6379:6379"


  backend:
    build: .
    container_name: ecommerce-backend

    environment:
      AWS_REGION: ap-southeast-1
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      JWT_EXPRIRATIONTIME: 604800000
      JWT_SECRETKEY: ${JWT_SECRETKEY}
      GHN_TOKEN: ${GHN_TOKEN}
      GHN_BASE-URL: ${GHN_BASE-URL}

      PAYMENT_VNPAY_TMNCODE: ${PAYMENT_VNPAY_TMNCODE}
      PAYMENT_VNPAY_VERSION: ${PAYMENT_VNPAY_VERSION}
      PAYMENT_VNPAY_PAYURL: ${PAYMENT_VNPAY_PAYURL}
      PAYMENT_VNPAY_RETURNURL: ${PAYMENT_VNPAY_RETURNURL}
      PAYMENT_VNPAY_COMMAND: ${PAYMENT_VNPAY_COMMAND}
      PAYMENT_VNPAY_ORDERTYPE: ${PAYMENT_VNPAY_ORDERTYPE}
      PAYMENT_VNPAY_HASHSECRET: ${PAYMENT_VNPAY_HASHSECRET}
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}

      GHN_CACHE_SHOP-TTL: 10
      GHN_CACHE_WARD_TTL: 1440
      GHN_CACHE_DISTRICT_TTL: 1440
      GHN_CACHE_PROVINCE_TTL: 1440
      GHN_CACHE_DEFAULT: 10

      API_PREFIX: /api/v1
    ports:
      - "8080:8080"

    depends_on:
      - postgres
      - redis


volumes:
  postgres_data: